import { dictionaryService, cleanTerm } from "./dictionary-service.js?v=5";

const STORAGE = "margin-reader-v1";
const TYPES = {
  word: { label: "生词", short: "生词" },
  phrase: { label: "短语 / 词组", short: "短语" },
  context: { label: "语境词", short: "语境" },
  sentence: { label: "句子 / 句式", short: "句式" },
};
const sampleDocuments = [{
  id: "modern-family-s01e01", title: "Modern Family · S01E01", source: "美剧台词",
  content: ["# Modern Family", "SCENE 01 · DUNPHY HOUSE", "", "Why are you guys yelling at us when we're way upstairs?", "Just text me.", "", "Luke got his head stuck in the banister again.", "", "It's on our bedside table...", "I don't know. Find it. Come on.", "", "No, Dad. You don't understand. Mom's been out all day and the baby is still in that thing."].join("\n"),
  annotations: [
    { id: "a-stuck", text: "stuck", type: "word", note: "卡住；被困住", example: "The drawer is stuck.", paragraphId: "p-4", startOffset: 18, endOffset: 23, createdAt: Date.now() },
    { id: "a-banister", text: "banister", type: "word", note: "楼梯扶手", example: "", paragraphId: "p-4", startOffset: 31, endOffset: 40, createdAt: Date.now() },
    { id: "a-bedside", text: "bedside table", type: "word", note: "床头柜", example: "", paragraphId: "p-5", startOffset: 11, endOffset: 24, createdAt: Date.now() },
    { id: "a-yelling", text: "yelling at us", type: "phrase", note: "对某人大喊大叫：yell at sb", example: "", paragraphId: "p-2", startOffset: 18, endOffset: 32, createdAt: Date.now() }
  ]
}];
const defaults = { documents: sampleDocuments, activeId: sampleDocuments[0].id, fontSize: 18, width: 760, focused: false, mode: "read", filters: [], annotationsHidden: false, repeatMarkers: false, positions: {}, search: "", sideSearch: "", sideAnnotationId: "", sortMode: "document", sortOpen: false, studyCollapsed: false, studyPanel: "annotations", aiDraft: "", aiContextSelection: "", aiInstruction: "", aiMessages: [], aiSettingsOpen: false, shelfOpen: true, shelfArchiveOpen: false, shelfGroupOpen: "", favoritesOpen: false, dictionaryOpen: false, dictionarySearch: "", dictionarySchemaVersion: 2, bookTermsOpen: false, settingsOpen: false, bookTermsSearch: "", globalTermsSearch: "", globalBookSourceId: "", globalBookTermsSearch: "", bookTermsType: "all", globalTermsType: "all", libraryHideExamples: false, librarySortMode: "document", librarySortOpen: false, libraryEntryView: "list", libraryDetailKey: "", libraryDetailCollapsed: false, libraryDetailEditing: false, globalLibraryView: "books" };
let state = hydrate(), pendingSelection = null, openAnnotation = null, annotationExpanded = false, activePopover = null, undoStack = [], searchIndex = 0, saveTimer, dictionaryPageResult = null, dictionaryPageStatus = "";
const dictionaryStatus = new Map();
function hydrate() { try { const stored = JSON.parse(localStorage.getItem(STORAGE)); if (stored && Array.isArray(stored.documents)) { const resetDictionaryData = stored.dictionarySchemaVersion !== 2, hydrated = { ...defaults, ...stored, dictionarySchemaVersion: 2, shelfOpen: true, globalLibraryView: stored.globalLibraryView === "sources" ? "books" : stored.globalLibraryView || "books", sideAnnotationId: "", sortOpen: false, librarySortOpen: false, documents: stored.documents.map((doc) => ({ ...doc, annotations: (doc.annotations || []).filter((annotation) => annotation.type !== "fragment").map((annotation) => ({ ...annotation, surfaceForm: annotation.surfaceForm || annotation.text, lemma: annotation.lemma || annotation.prototype || "", userRelations: annotation.userRelations || [], dictionaryData: resetDictionaryData || hasUnreadableDictionaryData(annotation.dictionaryData) ? null : annotation.dictionaryData || null, updatedAt: annotation.updatedAt || annotation.createdAt || Date.now() })) })) }; if (resetDictionaryData) localStorage.setItem(STORAGE, JSON.stringify(hydrated)); return hydrated; } } catch (_) {} return structuredClone(defaults); }
function persist() { localStorage.setItem(STORAGE, JSON.stringify(state)); }
function scheduleSave() { clearTimeout(saveTimer); saveTimer = setTimeout(persist, 180); }
function activeDoc() { return state.documents.find((doc) => doc.id === state.activeId) || state.documents[0]; }
function countWords(text) { return (text.match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g) || []).length; }
function escapeHTML(value) { const raw = typeof value === "object" && value !== null ? readableDictionaryText(value) : String(value ?? ""); const text = raw.includes("[object Object]") ? "暂未提供释义" : raw; return text.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[c]); }
function speakerIcon() { return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h3l4 3V7l-4 3H4Z"></path><path d="M15 9.2a4.2 4.2 0 0 1 0 5.6"></path><path d="M18 6.5a8 8 0 0 1 0 11"></path></svg>'; }
function editIcon() { return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16.8-.5 3.7 3.7-.5L19 8.2l-3.2-3.2L4 16.8Z"></path><path d="m13.9 6.9 3.2 3.2"></path></svg>'; }
function uid() { return "a-" + Date.now().toString(36) + Math.random().toString(36).slice(2, 7); }
function parseContent(content) {
  return content.replace(/\r/g, "").split(/\n/).filter((block) => block.trim()).map((block, index) => {
    const text = block.trim(); let kind = "paragraph", value = text;
    if (text.startsWith("# ")) { kind = "title"; value = text.slice(2); } else if (text.startsWith("## ")) { kind = "heading"; value = text.slice(3); } else if (/^(SCENE|CHAPTER|PART)\b/i.test(text)) kind = "scene";
    return { id: "p-" + index, kind, text: value };
  });
}
function progressFor(doc) { return Math.max(0, Math.min(100, Math.round((state.positions[doc.id] || 0) * 100))); }
function visibleAnnotations(doc) { return state.annotationsHidden ? [] : doc.annotations.filter((a) => !state.filters.length || state.filters.includes(a.type)); }
function annotationPosition(a, b) { const aPart = Number(String(a.paragraphId || "").replace(/^p-/, "")), bPart = Number(String(b.paragraphId || "").replace(/^p-/, "")); return (aPart - bPart) || (a.startOffset - b.startOffset) || ((a.createdAt || 0) - (b.createdAt || 0)); }
function annotationKey(annotation) { return annotation.type + "\u0000" + annotation.text; }
function displayTerm(annotation) { const surfaceForm = annotation.surfaceForm || annotation.text, lemma = String(annotation.lemma || annotation.prototype || "").trim(); return lemma && lemma !== surfaceForm ? surfaceForm + "（" + lemma + "）" : surfaceForm; }
function hasUnreadableDictionaryData(data) { try { return JSON.stringify(data || "").includes("[object Object]"); } catch (_) { return true; } }
function readableDictionaryText(value, seen = new Set()) {
  if (value == null) return "";
  if (typeof value === "string" || typeof value === "number") { const text = String(value).trim(); return text.includes("[object Object]") ? "" : text; }
  if (typeof value !== "object" || seen.has(value)) return "";
  seen.add(value);
  if (Array.isArray(value)) return [...new Set(value.map((item) => readableDictionaryText(item, seen)).filter(Boolean))].join("；");
  const preferred = ["definition", "text", "translation", "meaning", "gloss", "explain", "content", "value"];
  const fromPreferred = preferred.map((key) => readableDictionaryText(value[key], seen)).filter(Boolean).join("；");
  return fromPreferred || [...new Set(Object.values(value).map((item) => readableDictionaryText(item, seen)).filter(Boolean))].join("；");
}
function dictionaryPrimaryMeaning(annotation) { return readableDictionaryText(annotation.dictionaryData?.meanings?.[0]?.definitions?.[0]?.definition); }
function dictionaryPartOfSpeech(annotation) { return annotation.partOfSpeech || annotation.dictionaryData?.meanings?.[0]?.partOfSpeech || ""; }
function libraryMetaLabel(annotation) { return compactMeaning(annotation); }
function compactMeaning(annotation) { return readableDictionaryText(annotation.meaning || annotation.note || dictionaryPrimaryMeaning(annotation)) || (dictionaryStatus.get(annotation.id) === "loading" ? "正在查询词典…" : "暂未填写释义"); }
function dictionaryRelationWords(data, key, limit) { const meanings = Array.isArray(data?.meanings) ? data.meanings : [], values = [data?.[key], ...meanings.flatMap((meaning) => [meaning?.[key], ...(Array.isArray(meaning?.definitions) ? meaning.definitions.map((definition) => definition?.[key]) : [])])]; return [...new Set(values.flatMap((value) => Array.isArray(value) ? value : [value]).map((value) => readableDictionaryText(value)).flatMap((value) => value.split(/[;,，；]/)).map((value) => value.trim()).filter((value) => value && !value.includes("[object Object]")))].slice(0, limit); }
function renderDictionaryRelations(data) { const block = (label, words) => words.length ? '<div class="dictionary-relations"><b>' + label + '</b><span>' + words.map((word) => '<i>' + escapeHTML(word) + '</i>').join("") + '</span></div>' : "", synonyms = dictionaryRelationWords(data, "synonyms", 8), antonyms = dictionaryRelationWords(data, "antonyms", 6); return block("近义词", synonyms) + block("反义词", antonyms); }
function renderLibraryDictionarySummary(data) { const phonetic = readableDictionaryText(data?.phonetic), source = readableDictionaryText(data?.source?.label) || "词典来源", meta = [phonetic, source].filter(Boolean).map((value) => '<span>' + escapeHTML(value) + '</span>').join(""); return '<section class="library-dictionary-section"><h3>词典</h3>' + (meta ? '<div class="library-dictionary-meta">' + meta + '</div>' : "") + renderDictionaryRelations(data) + '</section>'; }
function pronunciationAttributes(term, dictionaryData) { return ' data-pronounce-term="' + escapeHTML(cleanTerm(term)) + '" data-pronounce-audio="' + escapeHTML(dictionaryData?.audio || "") + '"'; }
function dictionaryCanLookup(annotation) { return ["word", "phrase", "context"].includes(annotation.type) && countWords(annotation.text) <= 5; }
function renderDictionaryDetails(data, { compact = false } = {}) {
  if (!data) return "";
  const senses = (data.meanings || []).slice(0, compact ? 1 : 3), definitions = senses.map((meaning) => {
    const items = (meaning.definitions || []).slice(0, compact ? 1 : 2).map((item) => { const value = readableDictionaryText(item?.definition || item); return '<li><span>' + escapeHTML(value || "暂未提供释义") + '</span>' + (!compact && item?.example ? '<em>' + escapeHTML(readableDictionaryText(item.example)) + '</em>' : "") + '</li>'; }).join("");
    return '<div class="dictionary-sense">' + (meaning.partOfSpeech ? '<b>' + escapeHTML(meaning.partOfSpeech) + '</b>' : "") + '<ol>' + items + '</ol></div>';
  }).join("");
  const relations = !compact ? renderDictionaryRelations(data) : "";
  const source = data.source?.url ? '<a href="' + escapeHTML(data.source.url) + '" target="_blank" rel="noreferrer">' + escapeHTML(data.source.label || "词典来源") + '</a>' : '<span>' + escapeHTML(data.source?.label || "词典来源") + '</span>';
  if (!senses.length) return '<div class="dictionary-result-empty">没有找到可显示的释义。</div>';
  return '<div class="dictionary-result ' + (compact ? "is-compact" : "") + '"><div class="dictionary-meta"><span>' + [data.phonetic, data.lemma ? "原型：" + data.lemma : ""].filter(Boolean).map(escapeHTML).join(" · ") + '</span>' + source + '</div>' + senses + relations + '</div>';
}
async function ensureAnnotationDictionary(annotation) {
  if (!annotation || !dictionaryCanLookup(annotation) || dictionaryStatus.has(annotation.id)) return;
  if (annotation.dictionaryData && !hasUnreadableDictionaryData(annotation.dictionaryData)) return;
  if (annotation.dictionaryData) annotation.dictionaryData = null;
  dictionaryStatus.set(annotation.id, "loading");
  if (openAnnotation === annotation.id) showAnnotation(annotation.id);
  try {
    annotation.dictionaryData = await dictionaryService.lookup(annotation.text);
    if (!annotation.partOfSpeech) annotation.partOfSpeech = annotation.dictionaryData?.meanings?.[0]?.partOfSpeech || "";
    dictionaryStatus.set(annotation.id, "ready");
    annotation.updatedAt = Date.now();
    persist();
  } catch (error) {
    dictionaryStatus.set(annotation.id, error?.message === "not-found" ? "not-found" : "error");
  }
  if (state.favoritesOpen && state.libraryDetailKey) render();
  else if (openAnnotation === annotation.id) showAnnotation(annotation.id);
}
async function runDictionaryPageSearch(rawTerm) {
  const term = cleanTerm(rawTerm);
  state.dictionarySearch = term;
  dictionaryPageResult = null;
  if (!term) { dictionaryPageStatus = ""; render(); return; }
  dictionaryPageStatus = "loading";
  render();
  try {
    const result = await dictionaryService.lookup(term);
    if (!state.dictionaryOpen || state.dictionarySearch !== term) return;
    dictionaryPageResult = result;
    dictionaryPageStatus = "ready";
  } catch (error) {
    if (!state.dictionaryOpen || state.dictionarySearch !== term) return;
    dictionaryPageStatus = error?.message === "not-found" ? "not-found" : "error";
  }
  render();
}
function annotationExcerpt(doc, annotation) { const part = parseContent(doc.content).find((item) => item.id === annotation.paragraphId); if (!part || annotation.startOffset < 0 || annotation.endOffset > part.text.length) return escapeHTML(annotation.text); const before = part.text.slice(0, annotation.startOffset), sentenceStart = Math.max(...[".", "!", "?", "。", "！", "？"].map((mark) => before.lastIndexOf(mark))) + 1, after = part.text.slice(annotation.endOffset), endingOffset = after.search(/[.!?。！？]/), sentenceEnd = endingOffset < 0 ? part.text.length : annotation.endOffset + endingOffset + 1; return escapeHTML(part.text.slice(sentenceStart, annotation.startOffset).replace(/^\s+/, "")) + "<strong>" + escapeHTML(part.text.slice(annotation.startOffset, annotation.endOffset)) + "</strong>" + escapeHTML(part.text.slice(annotation.endOffset, sentenceEnd)); }
function uniqueAnnotations(annotations) { const seen = new Map(); annotations.slice().sort(annotationPosition).forEach((annotation) => { if (!seen.has(annotationKey(annotation))) seen.set(annotationKey(annotation), annotation); }); return [...seen.values()]; }
function isWordCharacter(char) { return /[A-Za-z0-9_]/.test(char || ""); }
function repeatedAnnotations(part, sources) {
  if (!state.repeatMarkers) return [];
  const localManual = sources.filter((annotation) => annotation.paragraphId === part.id), repeats = [], seen = new Set();
  sources.filter((annotation) => ["word", "phrase", "sentence"].includes(annotation.type) && annotation.text).forEach((annotation) => {
    let start = part.text.indexOf(annotation.text);
    while (start !== -1) {
      const end = start + annotation.text.length, needsBoundary = annotation.type === "word" || annotation.type === "phrase", hasBoundaryConflict = needsBoundary && (isWordCharacter(part.text[start - 1]) || isWordCharacter(part.text[end]));
      const overlapsManual = localManual.some((item) => start < item.endOffset && end > item.startOffset);
      const key = annotation.id + "\u0000" + start + "\u0000" + end;
      if (!hasBoundaryConflict && !overlapsManual && !seen.has(key)) { repeats.push({ ...annotation, startOffset: start, endOffset: end, repeat: true }); seen.add(key); }
      start = part.text.indexOf(annotation.text, start + Math.max(1, annotation.text.length));
    }
  });
  return repeats;
}
function searchSafe(query) { return query.split("").map((char) => "\\.^$|?*+()[]{}".includes(char) ? "\\" + char : char).join(""); }
function renderText(part, doc) {
  const sources = visibleAnnotations(doc), manual = sources.filter((a) => a.paragraphId === part.id && a.startOffset >= 0 && a.endOffset <= part.text.length && a.endOffset > a.startOffset), annotations = manual.concat(repeatedAnnotations(part, sources)), query = state.search.trim().toLowerCase(), points = [...new Set([0, part.text.length, ...annotations.flatMap((a) => [a.startOffset, a.endOffset])])].sort((a, b) => a - b), ranks = { sentence: 0, context: 1, phrase: 2, word: 3 };
  return points.slice(0, -1).map((start, index) => {
    const end = points[index + 1], active = annotations.filter((a) => a.startOffset <= start && a.endOffset >= end), text = part.text.slice(start, end);
    let markup = escapeHTML(text);
    if (!active.length && query) markup = markup.split(new RegExp("(" + searchSafe(query) + ")", "ig")).map((chunk) => chunk.toLowerCase() === query ? '<span class="search-hit">' + chunk + "</span>" : '<span class="plain">' + chunk + "</span>").join("");
    else if (!active.length) markup = '<span class="plain">' + markup + "</span>";
    active.sort((a, b) => ranks[b.type] - ranks[a.type]).forEach((annotation) => { markup = '<mark class="' + annotation.type + (annotation.repeat ? " repeat" : "") + '" data-annotation-id="' + annotation.id + '" title="' + (annotation.repeat ? "关联出现 · " : "") + TYPES[annotation.type].short + ' · ' + escapeHTML(annotation.text) + '">' + markup + "</mark>"; });
    return markup;
  }).join("");
}
function renderAnalysis(a) { return a.type !== "sentence" || !a.note ? "" : '<aside class="analysis-block" data-analysis-id="' + a.id + '"><span class="analysis-kicker">解析</span><strong>' + escapeHTML(a.text) + "</strong><p>" + escapeHTML(a.note) + "</p>" + (a.example ? "<em>例句： " + escapeHTML(a.example) + "</em>" : "") + '<button title="收起解析" data-action="close-analysis" data-close-analysis="' + a.id + '">×</button></aside>'; }
function renderReader() {
  const doc = activeDoc(), parts = parseContent(doc.content), titlePart = parts.find((p) => p.kind === "title");
  const body = parts.filter((p) => p.kind !== "title").map((p) => {
    const tag = p.kind === "heading" ? "h3" : "p", item = doc.annotations.find((a) => a.paragraphId === p.id && a.type === "sentence" && a.expanded);
    return '<' + tag + ' data-part-id="' + p.id + '" data-kind="' + p.kind + '">' + renderText(p, doc) + '</' + tag + ">" + (item ? renderAnalysis(item) : "");
  }).join("");
  return '<main class="reader" data-reader-document-id="' + escapeHTML(doc.id) + '"><header class="reader-header"><div class="reader-title"><h1>' + escapeHTML(doc.title) + "</h1><p>" + countWords(doc.content).toLocaleString() + " words · " + progressFor(doc) + '% read</p></div><div class="toolbar"><div class="mode-switch"><button class="mode-button ' + (state.mode === "read" ? "active" : "") + '" data-action="mode-read">阅读</button><button class="mode-button ' + (state.mode === "study" ? "active" : "") + '" data-action="mode-study">学习</button></div><button class="tool-button" title="减小字号" data-action="font-down">A−</button><button class="tool-button" title="增大字号" data-action="font-up">A+</button><button class="tool-button focus-button ' + (state.focused ? "active" : "") + '" title="' + (state.focused ? "退出专注模式" : "专注模式") + '" data-action="focus">' + (state.focused ? "退出专注" : "专注模式") + '</button><button class="tool-button icon search-button ' + (activePopover === "search" ? "active" : "") + '" title="搜索本文" data-action="search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="5.8"></circle><path d="m15.2 15.2 4.3 4.3"></path></svg></button><button class="tool-button icon ' + (activePopover === "filters" ? "active" : "") + '" title="标注筛选" data-action="filters">◉</button><button class="tool-button icon" title="更多" data-action="more">···</button></div></header><section class="reader-canvas"><article class="document-paper ' + (state.mode === "study" ? "study-mode" : "") + '"><div class="doc-intro"><h2>' + escapeHTML(titlePart ? titlePart.text : doc.title) + '</h2></div><div class="document-content" id="document-content">' + body + '</div></article></section>' + (state.mode === "study" && doc.annotations.length ? '<nav class="jumpbar"><button title="上一条标注" data-action="previous">↑</button><button title="下一条标注" data-action="next">↓</button></nav>' : "") + "</main>";
}
function renderSidebar() { return '<aside class="sidebar"><div class="brand"><span class="brand-mark"></span><span>Margin</span></div><button class="import-button" data-action="import">＋ 导入文档</button><button class="shelf-entry ' + (state.shelfOpen ? "active" : "") + '" data-action="shelf">书架</button><button class="favorites-entry ' + (state.favoritesOpen ? "active" : "") + '" data-action="favorites">词条库</button><button class="dictionary-entry ' + (state.dictionaryOpen ? "active" : "") + '" data-action="dictionary">词典</button><button class="settings-entry ' + (state.settingsOpen ? "active" : "") + '" data-action="settings">设置</button><div class="library-label">我的阅读</div><div class="document-list">' + state.documents.map((doc) => '<button class="document-row ' + (doc.id === state.activeId && !state.shelfOpen && !state.favoritesOpen && !state.dictionaryOpen && !state.bookTermsOpen && !state.settingsOpen ? "active" : "") + '" data-document-id="' + doc.id + '"><span class="document-title">' + escapeHTML(doc.title) + '</span><span class="document-meta"><span>' + doc.annotations.length + ' 条标注</span><span class="meta-divider">·</span><span>' + progressFor(doc) + '%</span></span></button>').join("") + '</div><p class="sidebar-foot">标注与阅读进度只保存在这台设备。<br>可以导入 TXT、Markdown、HTML 与 DOCX。</p></aside>'; }
function studyHeader() { return '<header class="study-head"><h2>侧栏</h2><button class="sidebar-collapse" data-action="toggle-study-sidebar" title="' + (state.studyCollapsed ? "展开侧栏" : "收起侧栏") + '">' + (state.studyCollapsed ? "‹" : "›") + "</button></header>"; }
function renderStudySidebar() {
  const doc = activeDoc(), aiOpen = state.studyPanel === "ai", query = state.sideSearch.trim().toLowerCase(), matching = doc.annotations.filter((a) => !query || (a.text + " " + a.note + " " + a.example).toLowerCase().includes(query)), list = uniqueAnnotations(matching), selectedSource = doc.annotations.find((a) => a.id === state.sideAnnotationId), selected = list.find((a) => a.id === state.sideAnnotationId || (selectedSource && annotationKey(a) === annotationKey(selectedSource))), order = Object.keys(TYPES), view = list.slice().sort((a, b) => state.sortMode === "type" ? (order.indexOf(a.type) - order.indexOf(b.type)) || annotationPosition(a, b) : annotationPosition(a, b));
  const sortMenu = state.sortOpen ? '<div class="side-sort-menu"><button class="side-sort-option ' + (state.sortMode === "document" ? "active" : "") + '" data-side-sort="document">按文章顺序</button><button class="side-sort-option ' + (state.sortMode === "type" ? "active" : "") + '" data-side-sort="type">按标注类型</button></div>' : "";
  const tabs = '<nav class="study-tabs"><button class="' + (!aiOpen ? "active" : "") + '" data-action="show-annotations">标注</button><button class="side-ai ' + (aiOpen ? "active" : "") + '" data-action="ask-ai" aria-label="问 AI"><span>✦</span> 问 AI</button>' + (aiOpen ? "" : '<button class="side-sort" data-action="toggle-side-sort">排序 <span>↕</span></button>' + sortMenu) + "</nav>";
  const listHTML = view.length ? '<div class="side-list">' + view.map((a, index) => (state.sortMode === "type" && index && view[index - 1].type !== a.type ? '<div class="side-type-divider" aria-hidden="true"></div>' : "") + '<div class="side-list-item ' + (selected?.id === a.id ? "selected" : "") + '" data-side-annotation-id="' + a.id + '" role="button" tabindex="0"><i class="' + a.type + '"></i><span>' + escapeHTML(displayTerm(a)) + '</span>' + (selected?.id === a.id ? '<button class="side-jump" data-action="jump-to-annotation" data-jump-annotation-id="' + a.id + '">跳转至原文 <b>↗</b></button>' : '<em>' + TYPES[a.type].short + '</em>') + "</div>").join("") + "</div>" : '<p class="side-empty">没有匹配的标注</p>';
  const aiHistory = (state.aiMessages || []).filter((message) => message.documentId === doc.id).map((message) => '<div class="ai-user-message"><b>' + escapeHTML(message.instruction || "自由提问") + '</b><p>' + escapeHTML(message.text) + '</p></div><div class="ai-pending-message">已发送，等待 AI 回复…</div>').join(""), aiOptions = ["单词解析", "句子分析", "语法分析", "总结段落"].map((option) => '<button class="' + (state.aiInstruction === option ? "active" : "") + '" data-action="ai-suggestion" data-ai-suggestion="' + option + '">' + option + "</button>").join(""), aiSettings = state.aiSettingsOpen ? '<div class="ai-chat-settings-menu"><button data-action="clear-ai-chat">清空当前文章对话</button></div>' : "";
  const aiBody = '<div class="study-body ai-chat-body"><section class="ai-chat"><header class="ai-chat-context"><div class="ai-chat-context-copy"><strong><i>✦</i> Margin AI</strong><small>基于当前文章 · ' + escapeHTML(doc.title) + '</small></div><div class="ai-chat-settings"><button data-action="toggle-ai-settings" title="对话设置" aria-label="对话设置"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.05 2.05-.06-.06A1.7 1.7 0 0 0 15.8 18.6a1.7 1.7 0 0 0-1.03 1.55v.09h-2.9v-.09a1.7 1.7 0 0 0-1.03-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06-2.05-2.05.06-.06A1.7 1.7 0 0 0 7.25 15a1.7 1.7 0 0 0-1.55-1.03h-.09v-2.9h.09A1.7 1.7 0 0 0 7.25 10a1.7 1.7 0 0 0-.34-1.88l-.06-.06L8.9 6l.06.06A1.7 1.7 0 0 0 10.84 6.4a1.7 1.7 0 0 0 1.03-1.55v-.09h2.9v.09A1.7 1.7 0 0 0 15.8 6.4a1.7 1.7 0 0 0 1.88-.34L17.74 6l2.05 2.05-.06.06A1.7 1.7 0 0 0 19.4 10a1.7 1.7 0 0 0 1.55 1.03h.09v2.9h-.09A1.7 1.7 0 0 0 19.4 15Z"></path></svg></button>' + aiSettings + '</div></header><div class="ai-chat-messages"><div class="ai-chat-message"><b>可以问我什么？</b><p>我可以帮你理解单词、句子和表达，也可以概括当前段落。</p></div>' + aiHistory + '</div><div class="ai-chat-tools"><div class="ai-chat-suggestions">' + aiOptions + '</div></div><div class="ai-chat-compose ' + (state.aiContextSelection ? "has-selection" : "") + '"><textarea id="ai-chat-input" placeholder="输入你想问的问题…">' + escapeHTML(state.aiDraft) + '</textarea><button type="button" data-action="ai-chat-send" title="发送"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 14-7-4 14-3-5-5-2Z"></path><path d="m12 12 7-7"></path></svg></button></div><p class="ai-chat-note">发送后将按所选方式向 AI 提问。</p></section></div>';
  return '<aside class="study-sidebar">' + studyHeader() + tabs + (aiOpen ? aiBody : '<div class="study-body"><div class="side-search"><span>⌕</span><input id="side-search" placeholder="搜索本文或标注…" value="' + escapeHTML(state.sideSearch) + '"></div>' + listHTML + "</div>") + "</aside>";
}
function typeTabs(counts, active, attribute) { return '<nav class="term-type-tabs">' + ["all"].concat(Object.keys(TYPES)).map((type) => '<button class="' + (active === type ? "active" : "") + '" ' + attribute + '="' + type + '">' + (type === "all" ? "全部" : TYPES[type].short) + ' <em>' + (type === "all" ? counts.all : counts[type]) + "</em></button>").join("") + "</nav>"; }
function countTypes(annotations) { return annotations.reduce((counts, annotation) => { counts.all += 1; counts[annotation.type] += 1; return counts; }, { all: 0, word: 0, phrase: 0, context: 0, sentence: 0 }); }
function entrySurface(annotation) { return annotation.surfaceForm || annotation.text; }
function aggregatedEntries() { const entries = new Map(); state.documents.forEach((doc) => doc.annotations.forEach((annotation) => { const surfaceForm = entrySurface(annotation), key = annotation.type + "\u0000" + surfaceForm; if (!entries.has(key)) entries.set(key, { key, annotation, surfaceForm, occurrences: [], sourceIds: new Set() }); const entry = entries.get(key); entry.occurrences.push({ doc, annotation }); entry.sourceIds.add(doc.id); })); return [...entries.values()].sort((a, b) => a.surfaceForm.localeCompare(b.surfaceForm, "en", { sensitivity: "variant" })); }
function renderBookTerms() {
  const doc = activeDoc(), all = uniqueAnnotations(doc.annotations), query = state.bookTermsSearch.trim().toLowerCase(), counts = countTypes(all), typeOrder = Object.keys(TYPES), filtered = all.filter((annotation) => (state.bookTermsType === "all" || annotation.type === state.bookTermsType) && (!query || (entrySurface(annotation) + " " + annotation.meaning + " " + annotation.note + " " + annotation.example + " " + annotationExcerpt(doc, annotation)).toLowerCase().includes(query))), sorted = filtered.slice().sort((a, b) => state.librarySortMode === "recent" ? (b.createdAt || 0) - (a.createdAt || 0) : state.librarySortMode === "type" ? (typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)) || annotationPosition(a, b) : annotationPosition(a, b));
  const sortLabels = { document: "文章顺序", recent: "最近标注", type: "标注类型" }, sortMenu = state.librarySortOpen ? '<div class="book-sort-menu"><button class="' + (state.librarySortMode === "document" ? "active" : "") + '" data-book-sort="document">按文章顺序</button><button class="' + (state.librarySortMode === "recent" ? "active" : "") + '" data-book-sort="recent">按最近标注</button><button class="' + (state.librarySortMode === "type" ? "active" : "") + '" data-book-sort="type">按标注类型</button></div>' : "";
  const rows = sorted.length ? sorted.map((annotation, index) => (state.librarySortMode === "type" && (!index || sorted[index - 1].type !== annotation.type) ? '<div class="book-type-heading">' + TYPES[annotation.type].short + '</div>' : "") + '<button class="book-term-row" data-book-annotation="' + annotation.id + '"><strong>' + escapeHTML(displayTerm(annotation)) + '</strong><span class="book-term-meta"><i class="' + annotation.type + '"></i>' + libraryMetaLabel(annotation) + '</span>' + (state.libraryHideExamples ? "" : '<p>' + annotationExcerpt(doc, annotation) + "</p>") + "</button>").join("") : '<div class="favorites-empty"><b>没有匹配的词条</b><p>尝试调整搜索或类型筛选。</p></div>';
  return '<main class="favorites-page book-terms-page"><header class="favorites-header"><div class="book-terms-title"><h1>本书词条</h1><p>' + escapeHTML(doc.title) + ' · ' + all.length + ' 个标注</p></div><button data-action="book-terms-close">返回阅读</button></header><section class="book-terms-content"><div class="favorites-toolbar compact-search"><span>⌕</span><input id="book-terms-search" placeholder="搜索词条、释义或原文…" value="' + escapeHTML(state.bookTermsSearch) + '"></div>' + typeTabs(counts, state.bookTermsType, "data-book-type") + '<div class="book-view-controls"><button class="example-toggle" data-action="toggle-library-examples">' + (state.libraryHideExamples ? "显示例句" : "隐藏例句") + '</button><div class="book-sort"><button data-action="toggle-library-sort">' + sortLabels[state.librarySortMode] + '</button>' + sortMenu + '</div></div><section class="book-term-list">' + rows + "</section></section></main>";
}
function renderGlobalEntryLayout(entries) { const key = (entry) => encodeURIComponent(entry.key); if (!entries.length) return '<div class="favorites-empty"><b>没有匹配的词条</b><p>在阅读中主动标注后，它会出现在这里。</p></div>'; if (state.libraryEntryView === "list") return '<section class="book-term-list global-entry-list">' + entries.map((entry, index) => (state.librarySortMode === "type" && (!index || entries[index - 1].annotation.type !== entry.annotation.type) ? '<div class="book-type-heading">' + TYPES[entry.annotation.type].short + "</div>" : "") + '<article class="book-term-row" data-library-entry-key="' + key(entry) + '"><strong>' + escapeHTML(displayTerm(entry.annotation)) + '</strong><span class="book-term-meta"><i class="' + entry.annotation.type + '"></i>' + libraryMetaLabel(entry.annotation) + '</span>' + (state.libraryHideExamples ? "" : '<p>' + annotationExcerpt(entry.occurrences[0].doc, entry.annotation) + "</p>") + "</article>").join("") + "</section>"; if (state.libraryEntryView === "compare") { const midpoint = Math.ceil(entries.length / 2), columns = [entries.slice(0, midpoint), entries.slice(midpoint)]; return '<section class="term-compare-table">' + columns.map((column) => '<div class="term-compare-panel">' + column.map((entry) => '<article data-library-entry-key="' + key(entry) + '"><strong>' + escapeHTML(displayTerm(entry.annotation)) + '</strong><span>' + escapeHTML(compactMeaning(entry.annotation)) + '</span></article>').join("") + "</div>").join("") + "</section>"; } if (state.libraryEntryView === "words") return '<section class="term-word-grid">' + entries.map((entry) => '<article data-library-entry-key="' + key(entry) + '">' + escapeHTML(displayTerm(entry.annotation)) + "</article>").join("") + "</section>"; return '<section class="term-card-grid">' + entries.map((entry) => '<article data-library-entry-key="' + key(entry) + '"><strong>' + escapeHTML(displayTerm(entry.annotation)) + '</strong><span class="book-term-meta"><i class="' + entry.annotation.type + '"></i>' + libraryMetaLabel(entry.annotation) + '</span><p>' + escapeHTML(compactMeaning(entry.annotation)) + '</p>' + (state.libraryHideExamples ? "" : '<em>' + annotationExcerpt(entry.occurrences[0].doc, entry.annotation) + "</em>") + "</article>").join("") + "</section>"; }
function renderLibraryEntryDetail(entry) {
  if (!entry) return "";
  if (state.libraryDetailCollapsed) return '<aside class="library-entry-detail is-collapsed" id="library-entry-detail"><button title="展开词条详情" data-action="toggle-library-entry-detail">‹</button></aside>';
  const annotation = entry.annotation, occurrence = entry.occurrences[0], meaning = readableDictionaryText(annotation.meaning || annotation.note || dictionaryPrimaryMeaning(annotation)) || "暂未填写释义", prototype = annotation.prototype || annotation.lemma;
  const editor = state.libraryDetailEditing ? '<form id="library-entry-detail-form" data-entry-key="' + encodeURIComponent(entry.key) + '"><section><h3>释义</h3><input name="meaning" placeholder="填写一条简要释义" value="' + escapeHTML(annotation.meaning || annotation.note || "") + '"></section><section><h3>原型</h3><input name="prototype" placeholder="例如 happen" value="' + escapeHTML(prototype || "") + '"></section><section><h3>备注</h3><textarea name="note" placeholder="写下你的理解…">' + escapeHTML(annotation.note || "") + '</textarea></section><div class="library-detail-save"><button type="button" data-action="toggle-library-entry-edit">取消</button><button type="submit">保存</button></div></form>' : '<section><h3>释义</h3><p>' + escapeHTML(meaning) + '</p></section>' + (prototype ? '<section><h3>原型</h3><p>' + escapeHTML(prototype) + '</p></section>' : "") + (annotation.meaning && annotation.note ? '<section><h3>备注</h3><p>' + escapeHTML(annotation.note) + '</p></section>' : "");
  const dictionary = annotation.dictionaryData ? renderLibraryDictionarySummary(annotation.dictionaryData) : dictionaryStatus.get(annotation.id) === "loading" ? '<section class="library-dictionary-section"><h3>词典</h3><p class="dictionary-loading">正在查询词典…</p></section>' : "";
  return '<aside class="library-entry-detail" id="library-entry-detail"><div class="library-detail-heading"><h2>词条详情</h2><button class="sidebar-collapse" title="收起详情" data-action="close-library-entry-detail">›</button></div><div class="library-detail-body"><header><div class="library-entry-title"><span class="library-entry-word"><strong>' + escapeHTML(displayTerm(annotation)) + '</strong><button class="pronunciation-button" title="播放美式读音" data-action="pronunciation"' + pronunciationAttributes(annotation.text, annotation.dictionaryData) + '>' + speakerIcon() + '</button></span><span><i class="' + annotation.type + '"></i>' + libraryMetaLabel(annotation) + '</span></div><div><button class="library-edit-button" title="编辑词条" data-action="toggle-library-entry-edit">' + editIcon() + '</button></div></header>' + editor + dictionary + '<section class="library-detail-example"><h3>文章例句</h3><small>' + escapeHTML(occurrence.doc.title) + '</small><p>' + annotationExcerpt(occurrence.doc, annotation) + '</p></section></div></aside>';
}
function renderFavorites() {
  const globalQuery = state.globalTermsSearch.trim().toLowerCase(), selectedBook = state.documents.find((doc) => doc.id === state.globalBookSourceId && doc.annotations.length), allEntries = aggregatedEntries(), visibleEntries = allEntries.filter((entry) => (state.globalTermsType === "all" || entry.annotation.type === state.globalTermsType) && (!globalQuery || (entry.surfaceForm + " " + entry.annotation.lemma + " " + entry.annotation.meaning + " " + entry.annotation.note).toLowerCase().includes(globalQuery))), counts = countTypes(allEntries.map((entry) => entry.annotation)), sourceCount = state.documents.filter((doc) => doc.annotations.length).length;
  const entryTypeOrder = Object.keys(TYPES), sortedEntries = visibleEntries.slice().sort((a, b) => state.librarySortMode === "recent" ? (b.annotation.createdAt || 0) - (a.annotation.createdAt || 0) : state.librarySortMode === "type" ? (entryTypeOrder.indexOf(a.annotation.type) - entryTypeOrder.indexOf(b.annotation.type)) || annotationPosition(a.annotation, b.annotation) : annotationPosition(a.annotation, b.annotation)), globalSortLabels = { document: "文章顺序", recent: "最近标注", type: "标注类型" }, globalSortMenu = state.librarySortOpen ? '<div class="book-sort-menu"><button class="' + (state.librarySortMode === "document" ? "active" : "") + '" data-book-sort="document">按文章顺序</button><button class="' + (state.librarySortMode === "recent" ? "active" : "") + '" data-book-sort="recent">按最近标注</button><button class="' + (state.librarySortMode === "type" ? "active" : "") + '" data-book-sort="type">按标注类型</button></div>' : "";
  const entriesView = renderGlobalEntryLayout(sortedEntries);
  const books = state.documents.filter((doc) => doc.annotations.length).filter((doc) => !globalQuery || (doc.title + " " + (doc.source || "")).toLowerCase().includes(globalQuery));
  const booksView = books.map((doc) => { const annotations = uniqueAnnotations(doc.annotations), typeCounts = countTypes(annotations), typeSummary = Object.keys(TYPES).filter((type) => typeCounts[type]).map((type) => TYPES[type].short + " " + typeCounts[type]).join(" · "); return '<button class="global-book-row" data-book-source="' + doc.id + '"><span class="global-book-details"><strong>' + escapeHTML(doc.title) + '</strong><em>' + escapeHTML(doc.source || "阅读文档") + (typeSummary ? " · " + typeSummary : "") + '</em></span><span class="global-book-count"><b>' + annotations.length + '</b><small>个词条</small></span><span class="global-book-arrow" aria-hidden="true">›</span></button>'; }).join("") || '<div class="favorites-empty"><b>' + (globalQuery ? "没有匹配的书目" : "还没有书目") + '</b><p>' + (globalQuery ? "尝试换一个书名或来源关键词。" : "先在文章中创建标注。") + "</p></div>";
  const collectionView = '<div class="favorites-empty global-collection-empty"><b>收藏夹</b><p>这里会用于放置你想单独保留的词条。</p></div>';
  const inlineBookView = selectedBook ? (() => { const query = state.globalBookTermsSearch.trim().toLowerCase(), all = uniqueAnnotations(selectedBook.annotations), typeOrder = Object.keys(TYPES), filtered = all.filter((annotation) => (state.bookTermsType === "all" || annotation.type === state.bookTermsType) && (!query || (entrySurface(annotation) + " " + annotation.meaning + " " + annotation.note + " " + annotation.example + " " + annotationExcerpt(selectedBook, annotation)).toLowerCase().includes(query))), sorted = filtered.slice().sort((a, b) => state.librarySortMode === "recent" ? (b.createdAt || 0) - (a.createdAt || 0) : state.librarySortMode === "type" ? (typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)) || annotationPosition(a, b) : annotationPosition(a, b)), sortLabels = { document: "文章顺序", recent: "最近标注", type: "标注类型" }, sortMenu = state.librarySortOpen ? '<div class="book-sort-menu"><button class="' + (state.librarySortMode === "document" ? "active" : "") + '" data-book-sort="document">按文章顺序</button><button class="' + (state.librarySortMode === "recent" ? "active" : "") + '" data-book-sort="recent">按最近标注</button><button class="' + (state.librarySortMode === "type" ? "active" : "") + '" data-book-sort="type">按标注类型</button></div>' : "", rows = sorted.length ? sorted.map((annotation, index) => (state.librarySortMode === "type" && (!index || sorted[index - 1].type !== annotation.type) ? '<div class="book-type-heading">' + TYPES[annotation.type].short + "</div>" : "") + '<button class="book-term-row" data-book-annotation="' + annotation.id + '"><strong>' + escapeHTML(displayTerm(annotation)) + '</strong><span class="book-term-meta"><i class="' + annotation.type + '"></i>' + libraryMetaLabel(annotation) + '</span>' + (state.libraryHideExamples ? "" : '<p>' + annotationExcerpt(selectedBook, annotation) + "</p>") + "</button>").join("") : '<div class="favorites-empty inline-book-empty"><b>没有匹配的词条</b><p>尝试调整搜索或类型筛选。</p></div>'; return '<section class="inline-book-terms"><header class="inline-book-head"><span><strong>' + escapeHTML(selectedBook.title) + '</strong></span><div class="inline-book-actions"><button class="example-toggle" data-action="toggle-library-examples">' + (state.libraryHideExamples ? "显示例句" : "隐藏例句") + '</button><div class="book-sort"><button data-action="toggle-library-sort">' + sortLabels[state.librarySortMode] + '</button>' + sortMenu + '</div><button data-action="global-book-back">‹ 返回书目</button></div></header>' + typeTabs(countTypes(all), state.bookTermsType, "data-book-type") + '<section class="book-term-list">' + rows + "</section></section>"; })() : "";
  const viewMenu = state.libraryViewOpen ? '<div class="book-sort-menu"><button class="' + (state.libraryEntryView === "list" ? "active" : "") + '" data-entry-view="list">列表模式</button><button class="' + (state.libraryEntryView === "cards" ? "active" : "") + '" data-entry-view="cards">卡片模式</button><button class="' + (state.libraryEntryView === "compare" ? "active" : "") + '" data-entry-view="compare">对照模式</button><button class="' + (state.libraryEntryView === "words" ? "active" : "") + '" data-entry-view="words">词块模式</button></div>' : "";
  const content = selectedBook ? inlineBookView : state.globalLibraryView === "books" ? '<section class="global-book-list">' + booksView + "</section>" : state.globalLibraryView === "entries" ? '<div class="term-tabs-row">' + typeTabs(counts, state.globalTermsType, "data-global-type") + '<div class="book-view-controls"><button class="example-toggle" data-action="toggle-library-examples">' + (state.libraryHideExamples ? "显示例句" : "隐藏例句") + '</button><div class="book-sort"><button data-action="toggle-library-sort">' + globalSortLabels[state.librarySortMode] + '</button>' + globalSortMenu + '</div><div class="book-sort"><button data-action="toggle-library-view">视图</button>' + viewMenu + '</div><button data-global-view="books">‹ 返回书目</button></div></div>' + entriesView : collectionView;
  const searchPlaceholder = selectedBook ? "搜索本书词条" : state.globalLibraryView === "books" ? "搜索书目" : state.globalLibraryView === "collection" ? "搜索收藏夹" : "搜索全部词条", searchValue = selectedBook ? state.globalBookTermsSearch : state.globalTermsSearch;
  const detailEntry = !selectedBook && state.globalLibraryView === "entries" ? allEntries.find((entry) => entry.key === state.libraryDetailKey) : null;
  return '<main class="favorites-page global-library-page ' + (detailEntry ? "has-library-detail" : "") + (detailEntry && state.libraryDetailCollapsed ? " is-library-detail-collapsed" : "") + '"><header class="favorites-header global-library-header"><div class="book-terms-title"><h1>词条库</h1><p>' + allEntries.length + ' 个词条 · 来自 ' + sourceCount + ' 本文档</p></div><div class="library-header-actions"><div class="library-header-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="5.8"></circle><path d="M15.2 15.2 19.5 19.5"></path></svg><input id="global-terms-search" placeholder="' + searchPlaceholder + '" value="' + escapeHTML(searchValue) + '"></div><button data-action="favorites-close">返回阅读</button></div></header><section class="book-terms-content"><nav class="global-view-tabs"><button class="' + (state.globalLibraryView === "books" ? "active" : "") + '" data-global-view="books">书目</button><button class="' + (state.globalLibraryView === "entries" ? "active" : "") + '" data-global-view="entries">词库</button><button class="' + (state.globalLibraryView === "collection" ? "active" : "") + '" data-global-view="collection">收藏夹</button></nav>' + content + "</section>" + renderLibraryEntryDetail(detailEntry) + "</main>";
}
function renderShelf() {
  const archived = state.shelfArchiveOpen, archiveCount = state.documents.filter((doc) => doc.completedAt).length, activeGroup = state.shelfGroupOpen, documents = state.documents.filter((doc) => archived ? doc.completedAt : !doc.completedAt).slice().sort((a, b) => Number(Boolean(b.pinned)) - Number(Boolean(a.pinned)) || String(a.title).localeCompare(String(b.title), "en")), bookCard = (doc, index) => '<button class="shelf-book" data-document-id="' + doc.id + '" data-shelf-document="' + doc.id + '"><span class="shelf-cover cover-' + index % 5 + '"><i>Margin</i>' + (doc.pinned ? '<span class="shelf-star" title="已置顶">★</span>' : "") + '<b>' + escapeHTML(doc.title) + '</b><em>' + escapeHTML(doc.source || "阅读文档") + '</em></span><strong>' + escapeHTML(doc.title) + '</strong><small>' + uniqueAnnotations(doc.annotations).length + ' 条标注 · ' + progressFor(doc) + '%</small></button>';
  const grouped = documents.filter((doc) => doc.group), groups = [...new Set(grouped.map((doc) => doc.group))].sort((a, b) => a.localeCompare(b, "zh")), groupCards = groups.map((group, index) => { const groupBooks = grouped.filter((doc) => doc.group === group), previews = groupBooks.slice(0, 4).map((doc, previewIndex) => '<span class="group-preview-cover cover-' + (index + previewIndex) % 5 + '"><b>' + escapeHTML(doc.title.slice(0, 18)) + '</b></span>').join(""); return '<button class="shelf-group-card" data-shelf-group-name="' + escapeHTML(group) + '"><span class="group-preview">' + previews + '</span><strong>' + escapeHTML(group) + '</strong><small>' + groupBooks.length + ' 本文档</small></button>'; }).join(""), visibleBooks = activeGroup ? documents.filter((doc) => doc.group === activeGroup) : documents.filter((doc) => !doc.group), books = visibleBooks.map(bookCard).join(""), empty = '<div class="shelf-empty"><b>' + (activeGroup ? "这个分组还没有文档" : archived ? "还没有读完的文档" : "书架还是空的") + '</b><p>' + (activeGroup ? "可在书籍右键菜单中移动到这个分组。" : archived ? "在书架右击文档并标记为读完，它会出现在这里。" : "导入一篇文章或一本书，开始阅读。") + "</p></div>", pageTitle = activeGroup || (archived ? "已读归档" : "书架"), subtitle = activeGroup ? visibleBooks.length + ' 本文档' : archived ? archiveCount + ' 本已读文档' : state.documents.filter((doc) => !doc.completedAt).length + ' 本文档 · 标注与进度保存在本机';
  return '<main class="shelf-page"><header class="shelf-header"><div><h1>' + escapeHTML(pageTitle) + '</h1><p>' + subtitle + '</p></div><div class="shelf-actions">' + (activeGroup ? '<button data-action="close-shelf-group">返回书架</button>' : '<button data-action="toggle-shelf-archive">' + (archived ? "返回书架" : "已读归档 " + archiveCount) + '</button>') + (archived || activeGroup ? "" : '<button data-action="import">＋ 导入文档</button>') + '</div></header><section class="shelf-content"><div class="shelf-grid">' + (activeGroup ? (books || empty) : (groupCards + books || empty)) + (archived || activeGroup ? "" : '<button class="shelf-add" data-action="import"><span>＋</span><b>导入文档</b></button>') + '</div></section></main>';
}
function renderDictionaryPage() {
  const query = state.dictionarySearch || "";
  let body = '<div class="dictionary-page-empty"><b>查询英文词典</b><p>输入单词或短语，查看美式发音、原型、词性、释义、例句和近反义词。查询不会加入词条库。</p></div>';
  if (dictionaryPageStatus === "loading") body = '<div class="dictionary-page-empty"><b>正在查询“' + escapeHTML(query) + '”</b><p>优先使用本地 ECDICT，缺失时自动尝试英文补充词典。</p></div>';
  if (dictionaryPageStatus === "not-found") body = '<div class="dictionary-page-empty"><b>没有找到“' + escapeHTML(query) + '”</b><p>请检查拼写，或尝试查询词语的原型。</p></div>';
  if (dictionaryPageStatus === "error") body = '<div class="dictionary-page-empty"><b>词典暂时不可用</b><p>请确认本地服务仍在运行后再试。</p></div>';
  if (dictionaryPageResult) body = '<article class="dictionary-page-card"><header><div><h2>' + escapeHTML(dictionaryPageResult.headword || dictionaryPageResult.term || query) + '</h2><p>查询结果不会自动保存为标注</p></div><button class="pronunciation-button" data-action="pronunciation" title="播放美式发音"' + pronunciationAttributes(dictionaryPageResult.headword || query, dictionaryPageResult) + '>' + speakerIcon() + '</button></header>' + renderDictionaryDetails(dictionaryPageResult) + '</article>';
  return '<main class="favorites-page dictionary-page"><header class="favorites-header"><div class="book-terms-title"><h1>词典</h1><p>本地英汉词典 · 美式发音</p></div><button data-action="dictionary-close">返回阅读</button></header><section class="dictionary-page-content"><form class="dictionary-page-search" id="dictionary-page-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="5.8"></circle><path d="M15.2 15.2 19.5 19.5"></path></svg><input id="dictionary-page-input" name="term" autocomplete="off" spellcheck="false" placeholder="输入英文单词或短语…" value="' + escapeHTML(query) + '"><button type="submit">查询</button></form>' + body + '</section></main>';
}
function renderSettings() { return `<main class="favorites-page settings-page"><header class="favorites-header"><h1>设置</h1><button data-action="settings-close">返回阅读</button></header><section class="favorites-content"><section class="settings-section"><h2>阅读偏好</h2><div class="settings-row"><span><strong>正文字号</strong><em>当前 ${state.fontSize}px</em></span><div><button data-action="font-down">A−</button><button data-action="font-up">A+</button></div></div><div class="settings-row"><span><strong>同文重复标记</strong><em>在当前文章中以淡蓝色显示相同词形的后续出现</em></span><button data-action="toggle-repeat-markers">${state.repeatMarkers ? "已开启" : "已关闭"}</button></div></section><section class="settings-section"><h2>词典与发音</h2><div class="settings-row"><span><strong>本地英汉词典</strong><em>ECDICT · 770,611 个词条，释义、词性和音标无需联网</em></span><b>已连接</b></div><div class="settings-row"><span><strong>在线英文补充</strong><em>本地未收录时再查询英文释义、例句和近反义词</em></span><b>自动</b></div><div class="settings-row"><span><strong>美式发音</strong><em>优先播放词典音频，缺失时使用系统 en-US 语音</em></span><b>美音</b></div></section><section class="settings-section"><h2>数据管理</h2><div class="settings-row"><span><strong>下载本地备份</strong><em>包括文档、标注、备注与阅读进度</em></span><button data-action="backup">下载</button></div><div class="settings-row danger"><span><strong>清空本地数据</strong><em>此操作不可撤销</em></span><button data-action="clear-data">清空</button></div></section><p class="settings-note">词典查询结果会在本机缓存 30 天；商业词典密钥不会保存在浏览器代码中。</p></section></main>`; }
function render() { const previousReader = document.querySelector(".reader"), previousDocumentId = previousReader?.dataset.readerDocumentId, previousTop = previousReader?.scrollTop || 0; document.documentElement.style.setProperty("--font-size", state.fontSize + "px"); document.documentElement.style.setProperty("--reading-width", "760px"); document.getElementById("app").innerHTML = '<div class="app-shell ' + (state.focused ? "is-focused" : "") + (state.studyCollapsed && !state.shelfOpen && !state.favoritesOpen && !state.dictionaryOpen && !state.bookTermsOpen && !state.settingsOpen ? " is-study-collapsed" : "") + '">' + renderSidebar() + (state.shelfOpen ? renderShelf() : state.dictionaryOpen ? renderDictionaryPage() : state.settingsOpen ? renderSettings() : state.bookTermsOpen ? renderBookTerms() : state.favoritesOpen ? renderFavorites() : renderReader() + renderStudySidebar()) + "</div>"; const restore = () => { const nextReader = document.querySelector(".reader"); if (nextReader && nextReader.dataset.readerDocumentId === previousDocumentId) nextReader.scrollTop = previousTop; }; restore(); requestAnimationFrame(restore); restoreOverlays(); }
function restoreReaderPosition() { const reader = document.querySelector(".reader"), pos = state.positions[state.activeId] || 0; if (reader) reader.scrollTo(0, pos * Math.max(0, reader.scrollHeight - reader.clientHeight)); }
function keepReaderScroll(callback) { const reader = document.querySelector(".reader"), top = reader?.scrollTop || 0; callback(); const restore = () => { const nextReader = document.querySelector(".reader"); if (nextReader) nextReader.scrollTop = top; }; restore(); requestAnimationFrame(restore); setTimeout(restore, 0); }
function toolbarRect() { return (document.querySelector('[data-action="filters"]') || document.querySelector(".toolbar")).getBoundingClientRect(); }
function showFilters() { const r = toolbarRect(), items = ["all", "none"].concat(Object.keys(TYPES)).map((type) => { const selected = type === "all" ? !state.annotationsHidden && !state.filters.length : type === "none" ? state.annotationsHidden : state.filters.includes(type); const label = type === "all" ? "全部标注" : type === "none" ? "隐藏全部标注" : TYPES[type].short; return '<button class="filter-option" data-filter="' + type + '"><span class="filter-check">' + (selected ? "✓" : "") + "</span>" + label + "</button>"; }).join(""); document.body.insertAdjacentHTML("beforeend", '<div class="popover" id="context-popover" style="top:' + (r.bottom + 8) + "px;left:" + Math.max(12, r.right - 220) + 'px"><div class="popover-title">显示哪些标注</div>' + items + "</div>"); }
function updateSearchCount() { const input = document.getElementById("search-input"), out = document.getElementById("search-count"); if (out) out.textContent = input && input.value ? document.querySelectorAll(".search-hit").length + " 处" : ""; }
function showSearch() { const r = toolbarRect(); document.body.insertAdjacentHTML("beforeend", '<div class="search-panel" id="context-popover" style="top:' + (r.bottom + 8) + "px;left:" + Math.max(12, r.right - 330) + 'px"><input id="search-input" autofocus placeholder="搜索本文" value="' + escapeHTML(state.search) + '"><span class="search-count" id="search-count"></span><button data-action="search-prev" title="上一处">↑</button><button data-action="search-next" title="下一处">↓</button><button class="search-close" data-action="search-close" title="退出搜索">×</button></div>'); updateSearchCount(); document.getElementById("search-input").focus(); }
function restoreOverlays() { document.getElementById("context-popover")?.remove(); if (activePopover === "filters") showFilters(); if (activePopover === "search") showSearch(); if (openAnnotation) showAnnotation(openAnnotation); }
function closeOverlays() { activePopover = null; pendingSelection = null; openAnnotation = null; annotationExpanded = false; document.querySelectorAll("#context-popover, #selection-toolbar, #annotation-popover, #side-context-menu, #shelf-context-menu, #group-picker, #lookup-card").forEach((e) => e.remove()); }
function showSideContextMenu(annotationId, x, y) { const left = Math.max(12, Math.min(window.innerWidth - 150, x)), top = Math.max(12, Math.min(window.innerHeight - 48, y)); document.body.insertAdjacentHTML("beforeend", '<div class="side-context-menu" id="side-context-menu" style="top:' + top + "px;left:" + left + 'px"><button data-action="delete-entry" data-entry-annotation-id="' + annotationId + '">删除标注</button></div>'); }
function showLibraryContextMenu(entryKey, x, y) { const entry = aggregatedEntries().find((item) => item.key === entryKey); if (!entry) return; const left = Math.max(12, Math.min(window.innerWidth - 150, x)), top = Math.max(12, Math.min(window.innerHeight - 48, y)); document.body.insertAdjacentHTML("beforeend", '<div class="side-context-menu" id="side-context-menu" style="top:' + top + "px;left:" + left + 'px"><button data-action="delete-library-entry" data-library-delete-key="' + encodeURIComponent(entryKey) + '">删除词条</button></div>'); }
function showShelfContextMenu(documentId, x, y) { const doc = state.documents.find((item) => item.id === documentId); if (!doc) return; const left = Math.max(12, Math.min(window.innerWidth - 168, x)), top = Math.max(12, Math.min(window.innerHeight - 239, y)), completion = doc.completedAt ? "恢复到书架" : "标记为读完", groupActions = doc.group ? '<button data-action="shelf-group-move" data-shelf-document="' + documentId + '">移动到其他分组</button><button data-action="shelf-group-remove" data-shelf-document="' + documentId + '">移出分组</button>' : '<button data-action="shelf-group" data-shelf-document="' + documentId + '">加入分组</button>'; document.body.insertAdjacentHTML("beforeend", '<div class="shelf-context-menu" id="shelf-context-menu" style="top:' + top + "px;left:" + left + 'px"><button data-action="shelf-pin" data-shelf-document="' + documentId + '">' + (doc.pinned ? "取消置顶" : "置顶") + '</button>' + groupActions + '<button data-action="shelf-complete" data-shelf-document="' + documentId + '">' + completion + '</button><i></i><button class="danger" data-action="shelf-clear-annotations" data-shelf-document="' + documentId + '">清空标记</button><button class="danger" data-action="shelf-delete" data-shelf-document="' + documentId + '">删除文档</button></div>'); }
function showGroupPicker(documentId) { const doc = state.documents.find((item) => item.id === documentId); if (!doc) return; const groups = [...new Set(state.documents.map((item) => item.group).filter((group) => group && group !== doc.group))].sort((a, b) => a.localeCompare(b, "zh")), choices = groups.length ? '<div class="group-picker-list">' + groups.map((group) => '<button data-action="shelf-select-group" data-shelf-document="' + documentId + '" data-group-name="' + escapeHTML(group) + '">' + escapeHTML(group) + '</button>').join("") + "</div>" : '<p class="group-picker-empty">还没有其他分组</p>'; document.body.insertAdjacentHTML("beforeend", '<section class="group-picker" id="group-picker"><header><strong>选择分组</strong><button data-action="close-group-picker" title="关闭">×</button></header>' + choices + '<div class="group-picker-new"><label for="group-new-name">新建分组</label><div><input id="group-new-name" placeholder="输入分组名称"><button data-action="shelf-new-group" data-shelf-document="' + documentId + '">新建</button></div></div></section>'); }
function showGroupContextMenu(group, x, y) { const count = state.documents.filter((doc) => doc.group === group).length, left = Math.max(12, Math.min(window.innerWidth - 168, x)), top = Math.max(12, Math.min(window.innerHeight - 52, y)); document.body.insertAdjacentHTML("beforeend", '<div class="shelf-context-menu" id="shelf-context-menu" style="top:' + top + "px;left:" + left + 'px"><button class="danger" data-action="shelf-group-delete" data-group-name="' + escapeHTML(group) + '">删除分组</button></div>'); }
function showSelectionToolbar() { document.getElementById("selection-toolbar")?.remove(); if (!pendingSelection) return; const r = pendingSelection.rect, buttons = Object.keys(TYPES).map((type) => '<button data-type="' + type + '">' + TYPES[type].short + "</button>").join(""); document.body.insertAdjacentHTML("beforeend", '<div class="floating" id="selection-toolbar" style="top:' + Math.max(8, r.top - 43) + "px;left:" + Math.max(8, Math.min(window.innerWidth - 410, r.left + r.width / 2 - 190)) + 'px">' + buttons + '<button class="floating-lookup" data-type="lookup" title="查询选中的内容"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="5.8"></circle><path d="m15.2 15.2 4.3 4.3"></path></svg><span>查询</span></button><i class="floating-divider" aria-hidden="true"></i><button class="floating-ai" data-type="ask-ai" title="使用 AI 提问"><span>✦</span> 问 AI</button><button class="floating-delete" data-type="delete" title="取消选择">×</button></div>'); }
function positionLookupCard(card, selection) {
  if (!card) return;
  const cardRect = card.getBoundingClientRect(), preferredTop = selection.rect.bottom + 10;
  card.style.left = Math.max(12, Math.min(window.innerWidth - cardRect.width - 12, selection.rect.left)) + "px";
  card.style.top = (preferredTop + cardRect.height <= window.innerHeight - 12 ? preferredTop : Math.max(12, selection.rect.top - cardRect.height - 10)) + "px";
}
async function showLookupCard(selection) {
  const requestId = uid(), term = cleanTerm(selection.text);
  document.body.insertAdjacentHTML("beforeend", '<section class="lookup-card" id="lookup-card" data-lookup-request="' + requestId + '"><header><strong>' + escapeHTML(term) + '</strong><span><button data-action="pronunciation" title="播放美式读音"' + pronunciationAttributes(term, null) + '>' + speakerIcon() + '</button><button data-action="close-lookup" title="关闭">×</button></span></header><div class="lookup-card-body"><p class="dictionary-loading">正在查询词典…</p></div></section>');
  positionLookupCard(document.getElementById("lookup-card"), selection);
  try {
    const data = await dictionaryService.lookup(term), card = document.querySelector('[data-lookup-request="' + requestId + '"]');
    if (!card) return;
    card.querySelector("[data-action=pronunciation]")?.setAttribute("data-pronounce-audio", data.audio || "");
    card.querySelector(".lookup-card-body").innerHTML = renderDictionaryDetails(data);
    positionLookupCard(card, selection);
  } catch (error) {
    const card = document.querySelector('[data-lookup-request="' + requestId + '"]');
    if (!card) return;
    card.querySelector(".lookup-card-body").innerHTML = '<div class="dictionary-result-empty"><b>' + (error?.message === "not-found" ? "没有查到这个词条" : "暂时无法连接词典") + '</b><span>仍可点击发音按钮使用系统美音。</span></div>';
    positionLookupCard(card, selection);
  }
}
function showAnnotation(id, anchor) {
  const a = activeDoc().annotations.find((item) => item.id === id), target = anchor || document.querySelector('[data-annotation-id="' + id + '"]'); if (!a || !target) return; openAnnotation = id; document.getElementById("annotation-popover")?.remove(); const r = target.getBoundingClientRect(), left = Math.max(12, Math.min(window.innerWidth - 344, r.left)), top = Math.min(window.innerHeight - 310, Math.max(12, r.bottom + 10)), parse = a.type === "sentence" ? '<button type="button" class="delete-note" data-action="toggle-analysis">' + (a.expanded ? "收起解析" : "展开解析") + "</button>" : "";
  const header = '<div class="annotation-head"><span class="annotation-title-wrap"><strong>' + escapeHTML(displayTerm(a)) + '</strong><button type="button" class="pronunciation-button" data-action="pronunciation" title="播放美式读音"' + pronunciationAttributes(a.text, a.dictionaryData) + '>' + speakerIcon() + '</button></span><button type="button" class="annotation-expand" data-action="toggle-annotation-card" title="' + (annotationExpanded ? "收起详情" : "展开详情") + '"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"></path></svg></button></div>';
  const compact = '<div class="annotation-compact">' + (dictionaryPartOfSpeech(a) ? '<span>' + escapeHTML(dictionaryPartOfSpeech(a)) + "</span>" : "") + '<div><p>' + escapeHTML(compactMeaning(a)) + "</p>" + (a.note && a.note !== a.meaning ? '<small>我的备注：' + escapeHTML(a.note) + "</small>" : "") + "</div></div>";
  const dictionary = a.dictionaryData ? '<div class="annotation-dictionary"><label>词典</label>' + renderDictionaryDetails(a.dictionaryData) + '</div>' : dictionaryStatus.get(a.id) === "loading" ? '<div class="annotation-dictionary"><label>词典</label><p class="dictionary-loading">正在查询词典…</p></div>' : dictionaryStatus.has(a.id) ? '<div class="annotation-dictionary"><label>词典</label><p class="dictionary-loading">' + (dictionaryStatus.get(a.id) === "not-found" ? "没有查到这个词条" : "暂时无法连接词典") + '</p></div>' : "";
  const editor = '<label>词性（可选）</label><input name="partOfSpeech" autocomplete="off" placeholder="例如 v.、n." value="' + escapeHTML(a.partOfSpeech || "") + '"><label>释义（可选）</label><input name="meaning" autocomplete="off" placeholder="填写一条简要释义" value="' + escapeHTML(a.meaning || "") + '"><label>原型（可选）</label><input name="prototype" autocomplete="off" spellcheck="false" placeholder="例如 happen" value="' + escapeHTML(a.prototype || "") + '"><label>备注</label><textarea name="note" placeholder="写下你的理解…">' + escapeHTML(a.note || "") + '</textarea><label>例句 / 补充</label><textarea name="example" placeholder="添加例句或补充…">' + escapeHTML(a.example || "") + '</textarea>' + dictionary + '<div class="annotation-actions">' + parse + '<span><button type="button" class="annotation-neutral" data-action="toggle-favorite">' + (a.favorited ? "取消收藏" : "收藏") + '</button><button class="annotation-neutral" type="submit">保存</button><button type="button" class="annotation-neutral" data-action="delete-annotation">删除</button></span></div>';
  document.body.insertAdjacentHTML("beforeend", '<form class="annotation-popover ' + (annotationExpanded ? "is-expanded" : "is-compact") + '" id="annotation-popover" style="top:' + top + "px;left:" + left + 'px">' + header + (annotationExpanded ? editor : compact) + "</form>");
  ensureAnnotationDictionary(a);
}
function selectionInfo() { const s = window.getSelection(); if (!s || s.isCollapsed || !s.toString().trim()) return null; const range = s.getRangeAt(0), asPart = (node) => (node.nodeType === 1 ? node : node.parentElement)?.closest("[data-part-id]"), part = asPart(range.commonAncestorContainer), start = asPart(range.startContainer), end = asPart(range.endContainer); if (!part || start !== end) { toast("第一版标注请在同一段落内选择文字"); return null; } const before = document.createRange(); before.selectNodeContents(part); before.setEnd(range.startContainer, range.startOffset); const bounds = range.getBoundingClientRect(), rect = { left: bounds.left, top: bounds.top, right: bounds.right, bottom: bounds.bottom, width: bounds.width, height: bounds.height }; return { paragraphId: part.dataset.partId, startOffset: before.toString().length, endOffset: before.toString().length + s.toString().length, text: s.toString().trim(), rect }; }
function createAnnotation(type) { if (type === "delete" || !pendingSelection) { window.getSelection().removeAllRanges(); closeOverlays(); return; } if (type === "lookup") { const selection = pendingSelection; closeOverlays(); window.getSelection().removeAllRanges(); showLookupCard(selection); return; } if (type === "ask-ai") { const selectedText = pendingSelection.text, wordCount = (selectedText.match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g) || []).length; closeOverlays(); window.getSelection().removeAllRanges(); state.studyPanel = "ai"; state.aiContextSelection = selectedText; state.aiDraft = selectedText; state.aiInstruction = wordCount > 1 ? "句子分析" : "单词解析"; keepReaderScroll(() => render()); setTimeout(() => document.getElementById("ai-chat-input")?.focus(), 0); return; } const doc = activeDoc(), p = pendingSelection, wordCount = (p.text.match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g) || []).length, resolvedType = type === "favorite" ? (wordCount >= 6 || /[.!?。！？]/.test(p.text) ? "sentence" : wordCount > 1 ? "phrase" : "word") : type; if (doc.annotations.some((a) => a.paragraphId === p.paragraphId && a.startOffset === p.startOffset && a.endOffset === p.endOffset)) { toast("这段文字已经有标注"); closeOverlays(); return; } const a = { id: uid(), text: p.text, surfaceForm: p.text, lemma: "", type: resolvedType, favorited: type === "favorite", partOfSpeech: "", meaning: "", note: "", example: "", userRelations: [], dictionaryData: null, paragraphId: p.paragraphId, startOffset: p.startOffset, endOffset: p.endOffset, createdAt: Date.now(), updatedAt: Date.now() }; doc.annotations.push(a); state.sideAnnotationId = a.id; undoStack.push({ documentId: doc.id, annotationId: a.id }); closeOverlays(); window.getSelection().removeAllRanges(); persist(); keepReaderScroll(() => render()); requestAnimationFrame(() => requestAnimationFrame(() => showAnnotation(a.id))); toast(type === "favorite" ? "已加入收藏夹" : "已标记为" + TYPES[resolvedType].short); }
function jumpSearch(dir) { const list = [...document.querySelectorAll(".search-hit")]; if (!list.length) return; searchIndex = (searchIndex + dir + list.length) % list.length; list[searchIndex].scrollIntoView({ behavior: "smooth", block: "center" }); }
function jumpAnnotation(dir) { const marks = [...document.querySelectorAll("[data-annotation-id]")]; if (!marks.length) return toast("此文档还没有标注"); const current = marks.findIndex((m) => m.getBoundingClientRect().top > 105), index = dir > 0 ? (current < 0 ? 0 : current) : (current <= 0 ? marks.length - 1 : current - 1); marks[index].scrollIntoView({ behavior: "smooth", block: "center" }); }
function toast(msg) { document.querySelector(".toast")?.remove(); document.body.insertAdjacentHTML("beforeend", '<div class="toast">' + escapeHTML(msg) + "</div>"); setTimeout(() => document.querySelector(".toast")?.remove(), 1800); }
function downloadBackup() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = "margin-backup.json"; link.click(); URL.revokeObjectURL(url); toast("本地备份已下载"); }
async function importFiles(files) { for (const file of files) { const ext = file.name.split(".").pop().toLowerCase(); if (["pdf", "epub"].includes(ext)) { toast("PDF / EPUB 解析结构已预留，当前 MVP 请使用 TXT、MD、HTML 或 DOCX"); continue; } let content = ""; if (ext === "docx") { if (!window.mammoth) { toast("DOCX 解析组件未加载，请检查网络后重试"); continue; } content = (await window.mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() })).value; } else { content = await file.text(); if (["html", "htm"].includes(ext)) content = new DOMParser().parseFromString(content, "text/html").body.innerText; if (["md", "markdown"].includes(ext)) content = content.replace(/^#{1,6}\s+/gm, "").replace(/[*_]{1,3}/g, ""); } if (!content.trim()) { toast(file.name + " 没有可阅读的文本"); continue; } const title = file.name.replace(/\.[^.]+$/, ""), doc = { id: "doc-" + Date.now().toString(36) + Math.random().toString(36).slice(2, 5), title, source: "导入文档", content, annotations: [] }; state.documents.unshift(doc); state.activeId = doc.id; state.positions[doc.id] = 0; } persist(); render(); window.scrollTo({ top: 0 }); }
document.addEventListener("click", (e) => {
  const action = e.target.closest(".sidebar [data-action]")?.dataset.action;
  if (action === "shelf") { e.stopPropagation(); state.shelfOpen = true; state.shelfArchiveOpen = false; state.shelfGroupOpen = ""; state.favoritesOpen = false; state.dictionaryOpen = false; state.bookTermsOpen = false; state.settingsOpen = false; persist(); render(); }
  if (action === "favorites") { e.stopPropagation(); state.shelfOpen = false; state.favoritesOpen = true; state.dictionaryOpen = false; state.bookTermsOpen = false; state.settingsOpen = false; state.globalBookSourceId = ""; state.globalTermsSearch = ""; persist(); render(); }
  if (action === "dictionary") { e.stopPropagation(); state.shelfOpen = false; state.favoritesOpen = false; state.dictionaryOpen = true; state.bookTermsOpen = false; state.settingsOpen = false; persist(); render(); setTimeout(() => document.getElementById("dictionary-page-input")?.focus(), 0); }
  if (action === "settings") { e.stopPropagation(); state.shelfOpen = false; state.settingsOpen = true; state.favoritesOpen = false; state.dictionaryOpen = false; state.bookTermsOpen = false; persist(); render(); }
}, true);
document.addEventListener("click", (e) => {
  const row = e.target.closest("[data-document-id]"); if (row) { state.activeId = row.dataset.documentId; state.shelfOpen = false; state.favoritesOpen = false; state.dictionaryOpen = false; state.bookTermsOpen = false; state.settingsOpen = false; closeOverlays(); persist(); render(); setTimeout(restoreReaderPosition, 0); return; }
  const shelfGroup = e.target.closest("[data-shelf-group-name]"); if (shelfGroup) { state.shelfGroupOpen = shelfGroup.dataset.shelfGroupName; render(); return; }
  const mark = e.target.closest("[data-annotation-id]"); if (mark) { e.stopPropagation(); const annotationId = mark.dataset.annotationId; state.sideAnnotationId = annotationId; activePopover = null; annotationExpanded = false; document.querySelectorAll("#context-popover, #selection-toolbar, #lookup-card").forEach((item) => item.remove()); showAnnotation(annotationId, mark); return; }
  const type = e.target.closest("[data-type]"); if (type) { createAnnotation(type.dataset.type); return; }
  const filter = e.target.closest("[data-filter]"); if (filter) { const v = filter.dataset.filter; if (v === "all") { state.annotationsHidden = false; state.filters = []; } else if (v === "none") { state.annotationsHidden = true; state.filters = []; } else { state.annotationsHidden = false; state.filters = state.filters.includes(v) ? state.filters.filter((x) => x !== v) : state.filters.concat(v); } persist(); render(); return; }
  const jumpTarget = e.target.closest("[data-jump-annotation-id]"); if (jumpTarget) { const targets = [...document.querySelectorAll('[data-annotation-id="' + jumpTarget.dataset.jumpAnnotationId + '"]')]; document.querySelectorAll(".jump-highlight").forEach((target) => target.classList.remove("jump-highlight")); targets.forEach((target) => target.classList.add("jump-highlight")); targets[0]?.scrollIntoView({ behavior: "smooth", block: "center" }); return; }
  const sideItem = e.target.closest("[data-side-annotation-id]"); if (sideItem) { state.sideAnnotationId = sideItem.dataset.sideAnnotationId; render(); return; }
  const favoriteItem = e.target.closest("[data-favorite-annotation]"); if (favoriteItem) { const ids = favoriteItem.dataset.favoriteAnnotation.split("|"); state.activeId = ids[0]; state.sideAnnotationId = ids[1]; state.shelfOpen = false; state.favoritesOpen = false; state.favoritesSearch = ""; persist(); render(); setTimeout(() => document.querySelector('[data-annotation-id="' + state.sideAnnotationId + '"]')?.scrollIntoView({ behavior: "smooth", block: "center" }), 0); return; }
  const bookItem = e.target.closest("[data-book-annotation]"); if (bookItem) return;
  const libraryEntry = e.target.closest("[data-library-entry-key]"); if (libraryEntry) { state.libraryDetailKey = decodeURIComponent(libraryEntry.dataset.libraryEntryKey); state.libraryDetailCollapsed = false; state.libraryDetailEditing = false; const entry = aggregatedEntries().find((item) => item.key === state.libraryDetailKey); render(); ensureAnnotationDictionary(entry?.annotation); return; }
  const sourceItem = e.target.closest("[data-book-source]"); if (sourceItem) { state.activeId = sourceItem.dataset.bookSource; state.globalBookSourceId = sourceItem.dataset.bookSource; state.globalBookTermsSearch = ""; state.bookTermsType = "all"; state.librarySortOpen = false; persist(); render(); return; }
  const sideType = e.target.closest("[data-side-type]"); if (sideType) { const a = activeDoc().annotations.find((x) => x.id === state.sideAnnotationId); a.type = sideType.dataset.sideType; persist(); render(); return; }
  const sideSort = e.target.closest("[data-side-sort]"); if (sideSort) { state.sortMode = sideSort.dataset.sideSort; state.sortOpen = false; persist(); render(); return; }
  const librarySort = e.target.closest("[data-library-sort]"); if (librarySort) { state.librarySortMode = librarySort.dataset.librarySort; state.librarySortOpen = false; persist(); render(); return; }
  const bookSort = e.target.closest("[data-book-sort]"); if (bookSort) { state.librarySortMode = bookSort.dataset.bookSort; state.librarySortOpen = false; persist(); render(); return; }
  const entryView = e.target.closest("[data-entry-view]"); if (entryView) { state.libraryEntryView = entryView.dataset.entryView; state.libraryViewOpen = false; persist(); render(); return; }
  const bookType = e.target.closest("[data-book-type]"); if (bookType) { state.bookTermsType = bookType.dataset.bookType; render(); return; }
  const globalType = e.target.closest("[data-global-type]"); if (globalType) { state.globalTermsType = globalType.dataset.globalType; render(); return; }
  const globalView = e.target.closest("[data-global-view]"); if (globalView) { state.globalLibraryView = globalView.dataset.globalView; state.globalBookSourceId = ""; state.globalBookTermsSearch = ""; state.libraryDetailKey = ""; render(); return; }
  const favoritesMode = e.target.closest("[data-favorites-mode]"); if (favoritesMode) { state.favoritesMode = favoritesMode.dataset.favoritesMode; state.favoritesTab = "all"; state.favoritesSearch = ""; render(); return; }
  const favoritesTab = e.target.closest("[data-favorites-tab]"); if (favoritesTab) { state.favoritesTab = favoritesTab.dataset.favoritesTab; state.favoritesSearch = ""; render(); return; }
  const action = e.target.closest("[data-action]")?.dataset.action; if (!action) { if (state.aiSettingsOpen && !e.target.closest(".ai-chat-settings")) { state.aiSettingsOpen = false; render(); return; } if (!e.target.closest("#annotation-popover, #lookup-card, #group-picker, #ai-chat, #library-entry-detail")) { const needsClear = state.sideAnnotationId || state.sortOpen || state.librarySortOpen || state.libraryDetailKey || document.querySelector(".jump-highlight"); closeOverlays(); if (needsClear && !e.target.closest("input, textarea, button")) { const selectedId = state.sideAnnotationId, selectedRow = selectedId && document.querySelector('[data-side-annotation-id="' + selectedId + '"]'); state.sideAnnotationId = ""; state.sortOpen = false; state.librarySortOpen = false; state.libraryDetailKey = ""; state.libraryDetailCollapsed = false; state.libraryDetailEditing = false; document.querySelectorAll(".jump-highlight").forEach((target) => target.classList.remove("jump-highlight")); if (selectedRow) { selectedRow.classList.remove("selected"); const jump = selectedRow.querySelector(".side-jump"); if (jump) { const annotation = activeDoc().annotations.find((item) => item.id === selectedId); jump.outerHTML = '<em>' + (annotation ? TYPES[annotation.type].short : "") + "</em>"; } } render(); } } return; }
  if (action === "toggle-annotation-card" && openAnnotation) { annotationExpanded = !annotationExpanded; showAnnotation(openAnnotation); return; }
  if (action === "pronunciation") { const button = e.target.closest("[data-action=pronunciation]"), term = button?.dataset.pronounceTerm || openAnnotation && activeDoc().annotations.find((item) => item.id === openAnnotation)?.text || ""; dictionaryService.pronounce(term, button?.dataset.pronounceAudio || "").catch(() => toast("当前浏览器无法播放读音")); return; }
  if (action === "close-lookup") { document.getElementById("lookup-card")?.remove(); return; }
  if (action === "close-library-entry-detail") { state.libraryDetailCollapsed = true; state.libraryDetailEditing = false; render(); return; }
  if (action === "toggle-library-entry-detail") { state.libraryDetailCollapsed = !state.libraryDetailCollapsed; render(); return; }
  if (action === "toggle-library-entry-edit") { state.libraryDetailEditing = !state.libraryDetailEditing; render(); return; }
  if (action === "ask-ai") { state.studyPanel = "ai"; render(); setTimeout(() => document.getElementById("ai-chat-input")?.focus(), 0); return; }
  if (action === "show-annotations") { state.studyPanel = "annotations"; render(); return; }
  if (action === "toggle-ai-settings") { state.aiSettingsOpen = !state.aiSettingsOpen; render(); return; }
  if (action === "clear-ai-chat") { if (window.confirm("清空这篇文章的全部 AI 对话记录？此操作不可撤销。")) { state.aiMessages = (state.aiMessages || []).filter((message) => message.documentId !== activeDoc().id); state.aiDraft = ""; state.aiContextSelection = ""; state.aiInstruction = ""; state.aiSettingsOpen = false; persist(); render(); toast("当前文章的对话已清空"); } return; }
  if (action === "ai-suggestion") { const suggestion = e.target.closest("[data-ai-suggestion]")?.dataset.aiSuggestion; if (suggestion) { state.aiInstruction = state.aiInstruction === suggestion ? "" : suggestion; keepReaderScroll(() => render()); setTimeout(() => document.getElementById("ai-chat-input")?.focus(), 0); } return; }
  if (action === "ai-chat-send") { const text = state.aiDraft.trim(); if (!text) { document.getElementById("ai-chat-input")?.focus(); return; } state.aiMessages = (state.aiMessages || []).concat({ id: uid(), documentId: activeDoc().id, text, instruction: state.aiInstruction }); state.aiDraft = ""; state.aiContextSelection = ""; state.aiInstruction = ""; persist(); keepReaderScroll(() => render()); return; }
  if (action === "shelf-pin") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument); if (doc) { doc.pinned = !doc.pinned; persist(); render(); toast(doc.pinned ? "已置顶" : "已取消置顶"); } return; }
  if (action === "shelf-group" || action === "shelf-group-move") { const doc = e.target.closest("[data-shelf-document]"); if (doc) { closeOverlays(); showGroupPicker(doc.dataset.shelfDocument); } return; }
  if (action === "shelf-group-remove") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument); if (doc) { doc.group = ""; persist(); render(); toast("已移出分组"); } return; }
  if (action === "shelf-select-group") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument), group = e.target.closest("[data-group-name]").dataset.groupName; if (doc && group) { doc.group = group; persist(); render(); toast("已移动到“" + group + "”"); } return; }
  if (action === "shelf-new-group") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument), input = document.getElementById("group-new-name"), group = input?.value.trim(); if (!group) { input?.focus(); return; } if (doc) { doc.group = group; persist(); render(); toast("已新建并加入“" + group + "”"); } return; }
  if (action === "close-group-picker") { document.getElementById("group-picker")?.remove(); return; }
  if (action === "shelf-group-delete") { const group = e.target.closest("[data-group-name]").dataset.groupName, count = state.documents.filter((doc) => doc.group === group).length; if (group && window.confirm("删除分组“" + group + "”会同时删除其中的 " + count + " 本文档及全部标注。此操作不可撤销。")) { state.documents = state.documents.filter((doc) => doc.group !== group); state.activeId = state.documents[0]?.id || ""; state.shelfGroupOpen = ""; persist(); render(); toast("分组及其中的文档已删除"); } return; }
  if (action === "shelf-complete") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument); if (doc) { doc.completedAt = doc.completedAt ? null : Date.now(); persist(); render(); toast(doc.completedAt ? "已移入已读归档" : "已恢复到书架"); } return; }
  if (action === "shelf-clear-annotations") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument); if (doc && window.confirm("清空“" + doc.title + "”中的全部标记？文档内容会保留。")) { doc.annotations = []; state.sideAnnotationId = state.activeId === doc.id ? "" : state.sideAnnotationId; persist(); render(); toast("这本文档的标记已清空"); } return; }
  if (action === "shelf-delete") { const doc = state.documents.find((item) => item.id === e.target.closest("[data-shelf-document]").dataset.shelfDocument); if (doc && window.confirm("删除“" + doc.title + "”及其全部标注？此操作不可撤销。")) { state.documents = state.documents.filter((item) => item.id !== doc.id); state.activeId = state.documents[0]?.id || ""; persist(); render(); toast("文档已删除"); } return; }
  if (action === "toggle-shelf-archive") { state.shelfArchiveOpen = !state.shelfArchiveOpen; render(); return; }
  if (action === "close-shelf-group") { state.shelfGroupOpen = ""; render(); return; }
  if (action === "import") { state.shelfOpen = false; state.settingsOpen = false; state.dictionaryOpen = false; state.bookTermsOpen = false; document.getElementById("file-input").click(); }
  if (action === "shelf") { state.shelfOpen = true; state.shelfArchiveOpen = false; state.shelfGroupOpen = ""; state.favoritesOpen = false; state.dictionaryOpen = false; state.bookTermsOpen = false; state.settingsOpen = false; persist(); render(); }
  if (action === "favorites") { state.shelfOpen = false; state.favoritesOpen = true; state.dictionaryOpen = false; state.bookTermsOpen = false; state.settingsOpen = false; state.globalBookSourceId = ""; state.globalTermsSearch = ""; persist(); render(); }
  if (action === "favorites-close") { state.shelfOpen = false; state.favoritesOpen = false; state.dictionaryOpen = false; state.globalBookSourceId = ""; state.globalTermsSearch = ""; persist(); render(); }
  if (action === "dictionary") { state.shelfOpen = false; state.favoritesOpen = false; state.dictionaryOpen = true; state.bookTermsOpen = false; state.settingsOpen = false; persist(); render(); setTimeout(() => document.getElementById("dictionary-page-input")?.focus(), 0); }
  if (action === "dictionary-close") { state.dictionaryOpen = false; dictionaryPageResult = null; dictionaryPageStatus = ""; persist(); render(); }
  if (action === "global-book-back") { state.globalBookSourceId = ""; state.globalBookTermsSearch = ""; state.bookTermsType = "all"; state.librarySortOpen = false; render(); }
  if (action === "book-terms") { state.shelfOpen = false; state.bookTermsOpen = true; state.favoritesOpen = false; state.dictionaryOpen = false; state.settingsOpen = false; state.bookTermsSearch = ""; persist(); render(); }
  if (action === "book-terms-close") { state.shelfOpen = false; state.bookTermsOpen = false; state.bookTermsSearch = ""; persist(); render(); }
  if (action === "settings") { state.shelfOpen = false; state.settingsOpen = true; state.favoritesOpen = false; state.dictionaryOpen = false; state.bookTermsOpen = false; persist(); render(); }
  if (action === "settings-close") { state.settingsOpen = false; persist(); render(); }
  if (action === "toggle-study-sidebar") { state.studyCollapsed = !state.studyCollapsed; persist(); render(); }
  if (action === "toggle-library-examples") { state.libraryHideExamples = !state.libraryHideExamples; persist(); render(); }
  if (action === "toggle-library-sort") { state.librarySortOpen = !state.librarySortOpen; state.libraryViewOpen = false; render(); }
  if (action === "toggle-library-view") { state.libraryViewOpen = !state.libraryViewOpen; state.librarySortOpen = false; render(); }
  if (action === "toggle-side-sort") { state.sortOpen = !state.sortOpen; render(); }
  if (action === "favorites-list" || action === "favorites-cards") { state.favoritesView = action === "favorites-list" ? "list" : "cards"; persist(); render(); }
  if (action === "backup") downloadBackup();
  if (action === "clear-data" && window.confirm("确定要清空所有本地文档、标注与设置吗？此操作无法撤销。")) { localStorage.removeItem(STORAGE); state = structuredClone(defaults); render(); toast("本地数据已清空"); }
  if (action === "font-down") { state.fontSize = Math.max(15, state.fontSize - 1); persist(); render(); }
  if (action === "font-up") { state.fontSize = Math.min(24, state.fontSize + 1); persist(); render(); }
  if (action === "toggle-repeat-markers") { state.repeatMarkers = !state.repeatMarkers; persist(); render(); }
  if (action === "focus") { state.focused = !state.focused; persist(); render(); }
  if (action === "mode-read" || action === "mode-study") { state.mode = action === "mode-read" ? "read" : "study"; persist(); render(); }
  if (action === "filters" || action === "search") { activePopover = activePopover === action ? null : action; openAnnotation = null; render(); }
  if (action === "search-close") { activePopover = null; state.search = ""; render(); }
  if (action === "previous") jumpAnnotation(-1); if (action === "next") jumpAnnotation(1); if (action === "search-prev") jumpSearch(-1); if (action === "search-next") jumpSearch(1); if (action === "more") toast("数据会自动保存在本机浏览器中");
  if (action === "side-save") { const a = activeDoc().annotations.find((x) => x.id === state.sideAnnotationId), value = document.getElementById("side-note").value.trim(), parts = value.split(/\n\s*\n例句：/); a.note = parts[0]; a.example = parts[1] || ""; persist(); render(); toast("备注已保存"); }
  if (action === "side-clear") { const input = document.getElementById("side-note"); if (input) input.value = ""; }
  if (action === "side-delete") { const doc = activeDoc(); doc.annotations = doc.annotations.filter((x) => x.id !== state.sideAnnotationId); state.sideAnnotationId = doc.annotations[0]?.id || null; persist(); render(); toast("标注已删除"); }
  if (action === "delete-entry") { const source = activeDoc().annotations.find((annotation) => annotation.id === e.target.closest("[data-entry-annotation-id]").dataset.entryAnnotationId); if (source && window.confirm("删除“" + source.text + "”及其在当前文章中的同类标注？")) { const key = annotationKey(source); activeDoc().annotations = activeDoc().annotations.filter((annotation) => annotationKey(annotation) !== key); state.sideAnnotationId = ""; closeOverlays(); persist(); render(); toast("标注已删除"); } }
  if (action === "delete-library-entry") { const target = e.target.closest("[data-library-delete-key]"), key = target ? decodeURIComponent(target.dataset.libraryDeleteKey) : "", entry = aggregatedEntries().find((item) => item.key === key); if (entry) { const sourceCount = new Set(entry.occurrences.map((occurrence) => occurrence.doc.id)).size, label = displayTerm(entry.annotation), scope = sourceCount > 1 ? "及它在 " + sourceCount + " 本文档中的全部同类标注" : "及它在文档中的全部同类标注"; if (window.confirm("删除词条“" + label + "”" + scope + "？")) { state.documents.forEach((doc) => { doc.annotations = doc.annotations.filter((annotation) => annotationKey(annotation) !== key); }); state.libraryDetailKey = ""; closeOverlays(); persist(); render(); toast("词条已删除"); } } return; }
  if (action === "toggle-favorite") { const a = activeDoc().annotations.find((x) => x.id === (openAnnotation || state.sideAnnotationId)); a.favorited = !a.favorited; persist(); if (openAnnotation) showAnnotation(a.id); else render(); toast(a.favorited ? "已加入收藏夹" : "已取消收藏"); }
  if (action === "delete-annotation" && openAnnotation) { const doc = activeDoc(); doc.annotations = doc.annotations.filter((a) => a.id !== openAnnotation); persist(); closeOverlays(); render(); toast("标注已删除"); }
  if (action === "toggle-analysis" && openAnnotation) { const a = activeDoc().annotations.find((x) => x.id === openAnnotation); a.expanded = !a.expanded; persist(); openAnnotation = null; render(); }
  if (action === "close-analysis") { const a = activeDoc().annotations.find((x) => x.id === e.target.dataset.closeAnalysis); a.expanded = false; persist(); render(); }
});
document.addEventListener("contextmenu", (e) => { const groupItem = e.target.closest("[data-shelf-group-name]"); if (groupItem) { e.preventDefault(); closeOverlays(); showGroupContextMenu(groupItem.dataset.shelfGroupName, e.clientX, e.clientY); return; } const shelfItem = e.target.closest("[data-shelf-document]"); if (shelfItem) { e.preventDefault(); closeOverlays(); showShelfContextMenu(shelfItem.dataset.shelfDocument, e.clientX, e.clientY); return; } const libraryItem = e.target.closest("[data-library-entry-key]"); if (libraryItem) { e.preventDefault(); closeOverlays(); showLibraryContextMenu(decodeURIComponent(libraryItem.dataset.libraryEntryKey), e.clientX, e.clientY); return; } const bookItem = e.target.closest("[data-book-annotation]"); if (bookItem) { const doc = state.documents.find((item) => item.id === state.globalBookSourceId) || activeDoc(), annotation = doc?.annotations.find((item) => item.id === bookItem.dataset.bookAnnotation); if (annotation) { e.preventDefault(); closeOverlays(); showLibraryContextMenu(annotationKey(annotation), e.clientX, e.clientY); } return; } const sideItem = e.target.closest("[data-side-annotation-id]"); if (!sideItem) return; e.preventDefault(); closeOverlays(); state.sideAnnotationId = sideItem.dataset.sideAnnotationId; render(); showSideContextMenu(state.sideAnnotationId, e.clientX, e.clientY); });
document.addEventListener("submit", (e) => { if (!e.target.matches("#annotation-popover")) return; e.preventDefault(); const a = activeDoc().annotations.find((x) => x.id === openAnnotation); a.partOfSpeech = e.target.partOfSpeech.value.trim(); a.meaning = e.target.meaning.value.trim(); a.prototype = e.target.prototype.value.trim(); a.lemma = a.prototype; a.note = e.target.note.value.trim(); a.example = e.target.example.value.trim(); a.updatedAt = Date.now(); persist(); openAnnotation = null; render(); toast("备注已保存"); });
document.addEventListener("submit", (e) => { if (!e.target.matches("#library-entry-detail-form")) return; e.preventDefault(); const entry = aggregatedEntries().find((item) => item.key === decodeURIComponent(e.target.dataset.entryKey)); if (!entry) return; const annotation = entry.annotation; annotation.meaning = e.target.meaning.value.trim(); annotation.prototype = e.target.prototype.value.trim(); annotation.lemma = annotation.prototype; annotation.note = e.target.note.value.trim(); annotation.updatedAt = Date.now(); state.libraryDetailEditing = false; persist(); render(); toast("词条已保存"); });
document.addEventListener("submit", (e) => { if (!e.target.matches("#dictionary-page-search")) return; e.preventDefault(); runDictionaryPageSearch(e.target.term.value); });
document.addEventListener("input", (e) => { if (e.target.id === "search-input") { state.search = e.target.value; searchIndex = 0; render(); } if (e.target.id === "side-search") { state.sideSearch = e.target.value; render(); document.getElementById("side-search")?.focus(); } if (e.target.id === "book-terms-search") { state.bookTermsSearch = e.target.value; render(); document.getElementById("book-terms-search")?.focus(); } if (e.target.id === "global-terms-search") { if (state.globalBookSourceId) state.globalBookTermsSearch = e.target.value; else state.globalTermsSearch = e.target.value; render(); document.getElementById("global-terms-search")?.focus(); } if (e.target.id === "dictionary-page-input") state.dictionarySearch = e.target.value; if (e.target.id === "ai-chat-input") { state.aiDraft = e.target.value; if (!state.aiDraft.trim()) { state.aiContextSelection = ""; e.target.closest(".ai-chat-compose")?.classList.remove("has-selection"); } } });
document.addEventListener("mouseup", (e) => { if (e.target.closest("#selection-toolbar") || e.target.closest(".toolbar")) return; setTimeout(() => { pendingSelection = selectionInfo(); showSelectionToolbar(); }, 0); });
document.addEventListener("keydown", (e) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "z" && undoStack.length) { e.preventDefault(); const last = undoStack.pop(), doc = state.documents.find((x) => x.id === last.documentId); doc.annotations = doc.annotations.filter((x) => x.id !== last.annotationId); persist(); closeOverlays(); render(); toast("已撤销上一次标注"); } if (e.key === "Escape") closeOverlays(); });
document.getElementById("file-input").addEventListener("change", (e) => { importFiles(e.target.files); e.target.value = ""; });
document.addEventListener("scroll", (e) => { const reader = e.target; if (!reader?.matches?.(".reader")) return; const max = Math.max(1, reader.scrollHeight - reader.clientHeight); state.positions[state.activeId] = Math.max(0, Math.min(1, reader.scrollTop / max)); scheduleSave(); }, true);
render();
setTimeout(restoreReaderPosition, 40);
